version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: williamcottrell72/travelapp:travelapp_v1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
      - "5432:5432"
    networks:
      - webnet
networks:
  webnet:
